#!/usr/bin/env python
"""Write docs/schema.md from the built tables: every table, its row count and its columns."""
import pandas as pd
import pyarrow.parquet as pq

from neon_beetle_seg import config
from neon_beetle_seg.build_ducklake import DESCRIPTIONS

tags = pd.read_csv(config.METADATA / "column_tags.csv")
notes = {(r.table, r.column): (r.note, r.curie, r.unit_curie if isinstance(r.unit_curie, str) else None)
         for r in tags.itertuples()}
META = {"taxon_terms": "NCBITaxon term for each scientific name (EMBL-EBI OLS4 lookup)",
        "landcover_terms": "ENVO term for each NLCD land-cover class",
        "obo_terms": "Every ontology term used in column tags",
        "column_tags": "Column -> ontology term and unit",
        "run_provenance": "Models, dataset revisions, package versions and git commit of this build"}
GROUPS = [
    ("NEON trap tables", lambda n: n.startswith("neon_") or n == "specimen_manifest"),
    ("Biorepository and GBIF", lambda n: n.startswith(("biorepo_", "gbif_"))),
    ("Images", lambda n: n.startswith("image_")),
    ("Segmentation results", lambda n: n in ("instances", "measurements")),
    ("Human annotations", lambda n: n in ("elytra_annotations_2018", "elytra_matches_2018", "tray_boxes_2018",
                                          "trait_annotations_hawaii", "hawaii_matches")),
    ("Validation", lambda n: n.startswith("validation_") or n == "sam3_comparison"),
    ("Ontology and provenance", lambda n: n in META),
]
files = {p.stem: p for p in sorted(config.TABLES.glob("*.parquet"))}
out = ["# Data dictionary", "",
       "Generated by `scripts/make_schema_doc.py` from the tables of the current build. Every table is in the",
       "lake (`ducklake/beetles.ducklake`), in the flat DuckDB file (`ducklake/beetles.duckdb`) and as a",
       "parquet file under `ducklake/export/`. The lake also has `table_catalog` (this list, as a table)",
       "and the view `individual_morphometrics` (`measurements` joined to `taxon_terms`).", ""]
seen = set()
for title, pick in GROUPS:
    names = [n for n in files if pick(n) and n not in seen]
    if not names:
        continue
    out += [f"## {title}", ""]
    for n in names:
        seen.add(n)
        pf = pq.ParquetFile(files[n])
        desc = DESCRIPTIONS.get(n, (META.get(n), None))[0]
        out += [f"### `{n}`", "", f"{desc or ''} {pf.metadata.num_rows:,} rows.".strip(), "",
                "| Column | Type | Meaning |", "|---|---|---|"]
        for f in pf.schema_arrow:
            note, curie, unit = notes.get((n, f.name), ("", None, None))
            tag = f" [{curie}{'; unit ' + unit if unit else ''}]" if curie else ""
            typ = str(f.type).replace("large_string", "string")
            out.append(f"| `{f.name}` | {typ} | {note}{tag} |")
        out.append("")
rest = [n for n in files if n not in seen]
if rest:
    out += ["## Other", ""] + [f"- `{n}`" for n in rest] + [""]
(config.ROOT / "docs" / "schema.md").write_text("\n".join(out))
print(f"docs/schema.md: {len(seen) + len(rest)} tables")
